[package]
name = "tlg-rs-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line tool for converting KrKr2 TLG images to and from common formats"
keywords = ["image", "tlg", "krkr", "converter", "cli"]
categories = ["command-line-utilities", "multimedia::images"]

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
flate2 = { version = "1.1.10", default-features = false, features = ["zlib-rs"] }
image = {
    version = "0.25.10", default-features = false,
    features = ["avif", "bmp", "dds", "jpeg", "png", "ff", "qoi", "pnm", "tga", "tiff", "rayon"]
}
tlg-rs = { path="..", version = "1.0.0" }

[[bin]]
name = "tlg-rs"
path = "src/main.rs"
