[package]
name = "tlg-rs-slide"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Internal crate for tlg-rs, do not use directly"

[lib]
name = "slide"

[dependencies]


[dev-dependencies]
criterion = { version = "0.8.2", features = ["csv_output", "html_reports"] }

[[bench]]
name = "bench"
harness = false
